#
# This workflow file is used for testing during local development with the help of
# https://github.com/nektos/act.
#

name: Test GH Action

on:
  workflow_dispatch:

jobs:
  test:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

      - name: Get Fields
        id: issue
        uses: ./
        with:
          retries: 1
          retryDelay: 10
          timeout: 2000
          issue: ${{ vars.JIRA_ISSUE }}

      - name: Print Output
        run: echo '${{ steps.issue.outputs.json }}'

      - name: Issue status is "To Do"
        if: fromJSON(steps.issue.outputs.json).fields.status.name == 'To Do'
        run: echo "Ticket is in 'To Do'"

      - name: Issue status is "In Progress"
        if: fromJSON(steps.issue.outputs.json).fields.status.name == 'In Progress'
        run: echo "Ticket is 'In Progress'"
