#
# This workflow file is used for testing during local development with the help of
# https://github.com/nektos/act.
#

name: Test GH Action

on:
  workflow_dispatch:

jobs:
  test:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

      - name: Get Fields
        id: issue
        uses: ./
        with:
          retries: 1
          retryDelay: 10
          timeout: 2000
          issue: ${{ vars.JIRA_ISSUE }}
          customFields: |
            previousStatus: 10858
            transitionStatus: 10859

      - name: Print Output
        run: |
          echo "Issue = ${{ steps.issue.outputs.issue }}"
          echo "Summary = ${{ steps.issue.outputs.summary }}"
          echo "Description = ${{ steps.issue.outputs.description }}"
          echo "Type = ${{ steps.issue.outputs.type }}"
          echo "Type ID = ${{ steps.issue.outputs.typeID }}"
          echo "Status = ${{ steps.issue.outputs.status }}"
          echo "Status ID = ${{ steps.issue.outputs.statusID }}"
          echo "Priority = ${{ steps.issue.outputs.priority }}"
          echo "Priority ID = ${{ steps.issue.outputs.priorityID }}"
          echo "Labels = ${{ steps.issue.outputs.labels }}"
          echo "Reporter Name = ${{ steps.issue.outputs.reporter }}"
          echo "Reporter ID = ${{ steps.issue.outputs.reporterID }}"
          echo "Assignee Name = ${{ steps.issue.outputs.assignee }}"
          echo "Assignee ID = ${{ steps.issue.outputs.assigneeID }}"
          echo "Components = ${{ steps.issue.outputs.components }}"
          echo "Previous Status = ${{ steps.issue.outputs.previousStatus }}"
          echo "Transition Status = ${{ steps.issue.outputs.transitionStatus }}"
          echo 'JSON = ${{ steps.issue.outputs.json }}'

      - name: Issue status is "To Do"
        if: steps.issue.outputs.status == 'To Do'
        run: echo "Ticket is in 'To Do'"

      - name: Issue status is "In Progress"
        if: steps.issue.outputs.status == 'In Progress'
        run: echo "Ticket is 'In Progress'"
